made it so that modifying the gmnotes of a handout modifies the import
TheGiddyLimit/5etoolsR20 pull request #151
Opened 2023-01-06 17:43 UTC by darthbeep

It used to be that if you modified the gmnotes the handout just broke, but now you can drag and drop a modified handout. Note that it only looks at the special `Vetoolscontent` category instead of the main one, which may be confusing, so if you think I should fix that I can, though it's a much larger fix. This also means handouts can't be easily modified for player import, as there is no simple way to access the part of the object.

2023-01-06 21:45 UTC, TheGiddyLimit commented
🤔 does this work if you have a `%` in the data and _don't_ edit the sheet, though? E.g. if you made a homebrew item with `60% of the time, it works every time` in the text and imported it/drag-dropped it to a sheet

2023-01-07 00:05 UTC, darthbeep commented
Yep, roll20 automatically escapes percent signs when encoding.

2023-01-10 12:13 UTC, TheGiddyLimit requested changes
It might, but we don't.

Fails to handle drag-drop of the following race: <https://raw.githubusercontent.com/TheGiddyLimit/homebrew/scratch/b20/race/Sample%20-%20Giddy%3B%20Awakened%20Skeleton.json>

Repro: Import it as a race handout from custom source, bind drag/drop, drop to sheet, see "URI malformed" error

2023-01-19 10:33 UTC, TheGiddyLimit approved these changes

2023-01-23 22:30 UTC, merged