Update 5etools-main.js
TheGiddyLimit/5etoolsR20 pull request #41
Opened 2021-06-17 21:02 UTC by Mertang

Giving the user the option to choose what sources to import features from when importing a class.

2021-06-23 09:16 UTC, Mertang commented
the second commit is irrelevant with the first. It provides better content for items when importing Packs.

2021-06-29 21:46 UTC, TheGiddyLimit requested changes
I don't like this. You're re-inventing the wheel: why pass in `["Player's Handbook (PHB)", "Tasha's Cauldron of Everything (TCE)", "Unearthed Arcana (UA)"]` to your `chooseSource` dialogue, when you could pass in e.g. `[SRC_PHB, SRC_TCE, SRC_UACFV]` then do a `${Parser.sourceJsonToFull(choice)} (${Parser.sourceJsonToAbv(choice)})` when you're rendering the choices.

(As a side note here, your current implementation of converting "UA" to "UAClassFeatureVariants" is inaccurate and therefore misleading to the user--there are other UA features/sub-features that the user might expect you to filter out, which you are not doing. I don't think you _should_ be doing it, since targeting the CFV UA seems a sensible/better choice for the moment, but, it would be better to inform the user of _precisely_ what they're signing up for.)

Also, why are you passing in a random `4` to the dialogue? It doesn't make any use of it. Looks a lot like you've copy-pasted this dialogue from somewhere else, and indeed, I see we now have two other copies of it in the code--I would prefer it, at this point, if you were to refactor it out to a utility method that could be called with arbitrary arguments (and maybe a "display function" parameter that would take in your input and render the option as output.

You're then doing a clunky `if (element === "Player's Handbook (PHB)") return "PHB"` loop check to get back the value you put in--if you passed in `SRC_PHB` in the first instance, you could simply return that.

---

Please note that I do like the idea of the change, and wish to see it get in, I would just like to see it cleaned up first. No time to mince words :^)

2021-07-16 11:34 UTC, TheGiddyLimit approved these changes

2021-07-25 18:18 UTC, merged

2021-07-25 18:33 UTC, TheGiddyLimit commented
Looks like I also merged this too soon; this change doesn't make any sense. 

If you import a homebrew class you now get no features, as none of them will have `"source": "PHB"`.